#稍后加载的项目配置文件

#spring配置
spring:
  #环境配置文件(dev/prd/test native代表本地)
  profiles:
    active: prd
  #当前服务名
  application:
    name: qizuo-admin
  #redis
  redis:
      database: 0 # Redis数据库索引（默认为0）
      host: ${ip} # Redis服务器地址
      password: null # Redis服务器连接密码（默认为空）
      port: 6379 # Redis服务器连接端口
      timeout: 5000 #超时时间
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 500 # 连接池中的最大空闲连接 默认 8
        max-wait: 1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
  #rabbitmq
  rabbitmq:
      host: ${ip} # 主机地址
      port: 5672 # 端口号
      username: guest # 用户名
      password: guest # 密码
      connection-timeout: 60 # 连接超时时间

#springboot配置
spring.boot:

#springboot配置
spring.cloud:

#端口 这个地方的配置是springboot内置tomcat的配置，如果采用war包即外部tomcat的方式，这个地方的配置不会生效
server:
  port: 9400
  context-path: /admin

#安全
security:
  basic:
    enabled: true #是否开启基本鉴权
  user:
    name: qizuo #鉴权用户名
    password: qizuo #鉴权密码

#是否打开SqlLogInterceptor
qizuo.interceptor.sqllog: false
#是否打开token
qizuo.interceptor.token: false
#token_rules
token_rules: false

#turbine监控配置
#turbine:
#  aggregator:
#    clusterConfig: default  #turbine监控的服务名称，可以多个
#  appConfig: qizuo-config,qizuo-zuul  #turbine监控的服务，可以有多个
#  clusterNameExpression: "'default'"