#基本配置
server:
  port: 8010 #端口
spring:
  profiles:
    active: prd #环境配置文件(dev/prd/test)
  application:
    name: qizuo-admin  #当前服务名

#swagger文档配置
swagger:
  title: qizuo-admin #swagger title
  description: qizuo-admin #swagger 描述

#springboot配置
spring.boot:
    #admin连接信息
    admin:
      username: qizuo
      password: qizuo