#基本配置
server:
  port: 7979 #端口
spring:
  profiles:
    active: prd #环境配置文件(dev/prd/test)
  application:
    name: qizuo-zuul #当前服务名
  boot:
      #admin连接信息
      admin:
        username: qizuo
        password: qizuo

#swagger文档配置
swagger:
  title: qizuo-zuul #swagger title
  description: qizuo-zuul #swagger 描述