#稍后加载的项目配置文件

#spring配置
spring:
  #环境配置文件(dev/prd/test native代表本地)
  profiles:
    active: prd
  #当前服务名
  application:
    name: qizuo-zuul
  #redis
  redis:
      database: 0 # Redis数据库索引（默认为0）
      host: ${ip} # Redis服务器地址
      password: null # Redis服务器连接密码（默认为空）
      port: 6379 # Redis服务器连接端口
      timeout: 5000 #超时时间
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-idle: 500 # 连接池中的最大空闲连接 默认 8
        max-wait: 1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        min-idle: 0 # 连接池中的最小空闲连接 默认 0
  #rabbitmq
  rabbitmq:
      host: ${ip} # 主机地址
      port: 5672 # 端口号
      username: guest # 用户名
      password: guest # 密码
      connection-timeout: 60 # 连接超时时间

#springboot配置
spring.boot:

#springboot配置
spring.cloud:

#端口
server:
  port: 9300
  context-path: /port

#安全
security:
  basic:
    enabled: true #是否开启基本鉴权
  user:
    name: qizuo #鉴权用户名
    password: qizuo #鉴权密码

#是否打开SqlLogInterceptor
qizuo.interceptor.sqllog: true
#是否打开token
qizuo.interceptor.token: true


#路由配置
zuul:
  #prefix: /port #路由匹配前缀
  ignored-services: '*' #先排除所有代理服务，只有以下配置的才会被路由代理
  routes:
    qizuo-config: #加密解密
      strip-prefix: false #是否去掉转发配置的前缀，比如这个地方是不去掉path前面的user
      path: /config/**
      serviceId: qizuo-config
    qizuo-provider-user: #用户认证服务
      strip-prefix: false #是否去掉转发配置的前缀，比如这个地方是不去掉path前面的user
      path: /user/**
      serviceId: qizuo-provider-user
      sensitiveHeaders: Cookie,Set-Cookie,Authorization #允许这些header
    qizuo-provider-user-admin: #用户信息修改服务
      strip-prefix: false
      path: /userAdmin/**
      serviceId: qizuo-provider-user-admin
    qizuo-provider-file: #上传服务
      strip-prefix: false
      path: /file/**
      serviceId: qizuo-provider-file
    qizuo-provider-qrcode: #二维码服务
        strip-prefix: false
        path: /qrcode/**
        serviceId: qizuo-provider-qrcode
    qizuo-provider-spider: #爬虫服务
        strip-prefix: false
        path: /spider/**
        serviceId: qizuo-provider-spider
    qizuo-provider-wx: #微信相关服务
        strip-prefix: false
        path: /wx/**
        serviceId: qizuo-provider-wx

#feign
feign:
  client:
    config:
      default:
        ConnectTimeOut: 10000 # 请求连接超时时间
        ReadTimeOut: 10000 #超时时间

# 断路器超时时间(需要配合@HystrixProperty注解使用，单独配置不起效果)
# hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 9000