import Vue from "vue";

import animate from "./animate";
Vue.component("qz-animate",animate);
import backToTop from "./backToTop";
Vue.component("qz-backToTop",backToTop);
import dialog from "./dialog";
Vue.component("qz-dialog",dialog);
import dialogForm from "./dialog/dialog_form";
Vue.component("qz-dialog-form",dialogForm);
import headerSearch from "./headerSearch";
Vue.component("qz-headerSearch",headerSearch);
import pagination from "./pagination";
Vue.component("qz-pagination",pagination);
import screenfull from "./screenfull";
Vue.component("qz-screenfull",screenfull);
import svgIcon from "./svgIcon";
Vue.component("qz-svgIcon",svgIcon);
import table from "./table";
Vue.component("qz-table",table);
import textHoverEffect from "./textHoverEffect";
Vue.component("qz-textHoverEffect",textHoverEffect);