#请不要使用tab键，使用空格键
#稍后加载的项目配置文件

#spring配置
spring:
  #环境配置文件(dev/prd/test)
  profiles:
    active: prd
  #当前服务名
  application:
    name: qizuo-provider-wx
  #redis
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: ${ip} # Redis服务器地址
    password: null # Redis服务器连接密码（默认为空）
    port: 6379 # Redis服务器连接端口
    timeout: 5000 #超时时间
    pool:
      max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-idle: 500 # 连接池中的最大空闲连接 默认 8
      max-wait: 1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
      min-idle: 0 # 连接池中的最小空闲连接 默认 0
  #rabbitmq
  rabbitmq:
    host: ${ip} # 主机地址
    port: 5672 # 端口号
    username: guest # 用户名
    password: guest # 密码
    connection-timeout: 60 # 连接超时时间
  #aop设置
  aop:
    #默认代理是接口代理，这个设置成实现类代理，可以解决事务因为service没有接口的问题
    proxy-target-class: true
  #devtools
  devtools:
    restart:
      enabled: false  #设置开启热部署
      additional-paths: qizuo-provider-wx/src/main/java #重启目录
      exclude: WEB-INF/**
  #上传文件大小限制
  servlet:
    multipart:
      max-request-size: 20MB #上传文件总的最大值
      max-file-size: 10MB #单个文件的最大值
  #数据库配置
  datasource:
    # 数据库访问配置, 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${ip}:3306/qizuo_file?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: qizuo
    druid:
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.springboot.servie.*
      # WebStatFilter配置，网络统计以及监控
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      # StatViewServlet配置 提供监控信息展示的html页面 提供监控信息的JSON API
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台
        login-username: druid
        login-password: druid123
        # IP白名单
        # allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218
      # 配置StatFilter 用于统计监控信息
      filter:
        stat:
          log-slow-sql: true
  #是否开启favicon图标访问
  mvc:
    favicon:
      enabled: false

#springboot配置
spring.boot:
  #admin连接信息
  admin:
    username: qizuo
    password: qizuo

#springboot配置
spring.cloud:

#mybatis配置
mybatis:
  mapperLocations: classpath*:mapper/*.xml #xml位置

#端口
server:
  port: 9940
  context-path: /wx

#安全
security:
  basic:
    enabled: true #是否开启基本鉴权
  user:
    name: qizuo #鉴权用户名
    password: qizuo #鉴权密码

# 保证调用 /refresh的时候不需要验证 暴露/refresh /bus-refresh接口,注意有风险，会暴露其它接口
management.security.enabled: false

#swagger文档配置
swagger:
  title: qizuo-provider-wx #swagger title
  description: qizuo-provider-wx #swagger 描述

wx:
  mp:
    useRedis: false
    redisConfig:
      host: 127.0.0.1
      port: 6379
    configs:
      - appId: 1111 # 第一个公众号的appid
        secret: 1111 # 公众号的appsecret
        token: 111 # 接口配置里的Token值
        aesKey: 111 # 接口配置里的EncodingAESKey值
      - appId: 2222 # 第二个公众号的appid，以下同上
        secret: 1111
        token: 111
        aesKey: 111

#是否打开SqlLogInterceptor
qizuo.interceptor.sqllog: true
#是否打开token
qizuo.interceptor.token: true
#配置store模式,支持jwt和redis两种,主要是jwt
qizuo.security.oauth2.token: jwt
#是否开启debug模式
debug: false